# Site configurations
title: Textos para Shiori
description: Eis aqui uma petit coleção de textos aleatórios~
url: https://nereare.github.io/texts/
logo: /assets/logo.jpg
locale: pt_BR
author:
  name: Igor Padoim
  email: igorpadoim@gmail.com
  picture: /assets/igor.jpg
  url: https://padoim.com.br/
license:
  name: Creative Commons BY-NC-SA 4.0 International
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt-br
show_excerpts: true

# Sass configurations
sass:
  quiet_deps: true
  style: compressed
  sourcemap: development

# Collections
collections:
  characters:
    output: true
  monsters:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship
  - liquid_reading_time
# Jekyll-spaceship configurations
jekyll-spaceship:
  processors:
    - table-processor
    - mermaid-processor
    - emoji-processor
  mermaid-processor:
    mode: default
    syntax:
      code: 'mermaid'
# Jekyll-feed configurations
feed:
  tags: true
  posts_limit: 25
  collections:
    - characters
    - monsters

# Exclusions
exclude:
  - .git/
  - .github/
  - .jekyll-cache/
  - .ruby-lsp/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
  - .gitattributes
  - README.md
  - LICENSE.md
  - OGL.md
  - CONTRIBUTING.md
